apiVersion: kueue.openshift.io/v1
kind: Kueue
metadata:
  name: cluster
spec:
  managementState: Managed
  logLevel: Normal
  operatorLogLevel: Normal
  config:
    preemption:
      preemptionPolicy: FairSharing
    integrations:
      frameworks:
        - BatchJob
        - JobSet
        - Pod
        - Deployment
        - StatefulSet
        - RayJob
        - RayCluster
        - PyTorchJob
        - LeaderWorkerSet
    workloadManagement:
      labelPolicy: ""
