apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - kueue.yaml
  - namespace-llm.yaml
  - resourceflavors.yaml
  - clusterqueue.yaml
  - localqueue.yaml
